### ISSUE TITLE
change button text from "download info pack" to "contact"

### ISSUE THREAD

**Issue by isysd** [TigoCTM/tigoctm#11]
MVP release won't have an information pack, just scroll to the contact form at the bottom.

**Comment by glenkow** [comment]
Button text should say "Request more Information" and scroll to the contact form at the bottom of the webpage.

**Comment by indieinc** [comment]
## Tasks
- [ ] Change button text to "Request More Information"
- [ ] Add function: on click, scroll to contact form at the bottom of the page

**Comment by isysd** [comment]
# Git Guild Bounty Program

| Total | Dev               | Sales | Reporter | Tester(s) | Maintainer | Documenter |
|--------|------------------|---------|-------------|------------|-----------------|----------------|
|N/A    | assignee(s)   | @isysd  | @isysd | @cindy-zimmerman, @d3brouille | @cindy-zimmerman | @d3brouille |
| $40 | $2 | $2 | $24 | $8 | $2 | $2 |
