### ISSUE TITLE
Infographic issues

### ISSUE THREAD

**Issue by indieinc** [TigoCTM/tigoctm#15]
## Rendering/Sizing Issues

- [ ] Renders differently depending on the browser it's viewed through. 
- [ ] Elements are sized relative to the dimensions of the browser window, which causes issues when the graphics stretch to fill the window. (Chrome seems to handle this better than Firefox.)
- [ ] The curved portions and the "START" line are cut off when the browser window is maximized in 1920x1080. However, a lower width results in these elements appearing as intended.
- [ ] On the first row, the account graphic is not aligned with the top of the ATM graphic.
- [ ] Empty white space at the bottom of the infographic should be removed
***

#### Firefox:

![test_10_1_info_ff](https://cloud.githubusercontent.com/assets/8877085/16738618/757d5cfe-4764-11e6-83b3-8a5dbc826a11.png)
![test_10_1_info2_ff](https://cloud.githubusercontent.com/assets/8877085/16738959/f9781818-4765-11e6-8ee1-f3b5594a84a4.png)

***

#### Chrome:

![test_10_1_info_cr](https://cloud.githubusercontent.com/assets/8877085/16738710/ed2db226-4764-11e6-882e-2802f7632b48.png)
![test_10_1_info2_cr](https://cloud.githubusercontent.com/assets/8877085/16738968/01e50b32-4766-11e6-9c46-5fe10a7a42f0.png)

**Comment by isysd** [comment]
# Git Guild Bounty Program

| Total | Dev               | Sales | Reporter | Tester(s) | Maintainer | Documenter |
|--------|------------------|---------|-------------|------------|-----------------|----------------|
|N/A    | assignee(s)   | @isysd  | @indieinc | @indieinc, @d3brouille | @cindy-zimmerman | @d3brouille |
| $165 | $99 | $8.25 | $8.25 | $33 | $8.25 | $8.25 |

**Comment by isysd** [comment]
@luisvillara I'm going to merge your PR #35, but it doesn't resolve all of the issues described above. In particular, resizing to small screens makes the text unreadable.

![small_tigoctm](https://cloud.githubusercontent.com/assets/1041868/16895927/f5b4d710-4b49-11e6-9454-0f0a1b0fa483.png)
