### ISSUE TITLE
Information button functionality

### ISSUE THREAD

**Issue by indieinc** [TigoCTM/tigoctm#18]
## Description
Button should scroll to the contact form at the bottom of the page. Change button text as referenced in #11 .

## Tasks
- [ ] Add function: on click, scroll to contact form at the bottom of the page
- [ ] Change button text to "Request More Information"

**Comment by isysd** [comment]
# Git Guild Bounty Program

| Total | Dev               | Sales | Reporter | Tester(s) | Maintainer | Documenter |
|--------|------------------|---------|-------------|------------|-----------------|----------------|
|N/A    | assignee(s)   | @isysd  | @indieinc | @indieinc, @d3brouille | @cindy-zimmerman | @d3brouille |
| $40 | $24 | $2 | $2 | $8 | $2 | $2 |

**Comment by mobymarto** [comment]
@isysd can you check this issue with this PR #33? We'd updated the issue description, but you were :ninja:

**Comment by isysd** [comment]
It looks good now! +1
