### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by indieinc** [TigoCTM/tigoctm#23]
## Description

The site needs a small version of the TigoCTM logo for a favicon. The favicon should be applied to all pages.

## Tasks

- [ ] Create a favicon from the TigoCTM logo
- [ ] Apply the favicon site-wide

**Comment by isysd** [comment]
# Git Guild Bounty Program

| Total | Dev               | Sales | Reporter | Tester(s) | Maintainer | Documenter |
|--------|------------------|---------|-------------|------------|-----------------|----------------|
|N/A    | assignee(s)   | @isysd  | @indieinc | @indieinc, @d3brouille | @cindy-zimmerman | @d3brouille |
| $40 | $24 | $2 | $2 | $8 | $2 | $2 |
