### ISSUE TITLE
footer with social media icons

### ISSUE THREAD

**Issue by isysd** [TigoCTM/tigoctm#38]
Make a footer to go below the contact form. The footer will have at minimum room for links and social media icons.
- [ ] Twitter
- [ ] Facebook
- [ ] Youtube
- [ ] Instagram
- [ ] Pinterest

**Comment by glenkow** [comment]
Commenting here because I don't think they warrant a new issue (and can be done at the same time). Let me know if you'd prefer new issues entered instead.

1.  Remove random characters at bottom of page "^ @ [return]"
2. Add Terms of Service, Privacy Policy, and Earnings Disclaimer Links.
